version: '3'

services:
  web:
    image: snipe/snipe-it:v6.1.0
    env_file:
      - ./.env
    volumes:
      - ./snipeit-vol:/var/lib/snipeit
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    restart: always

  mysql:
    image: mysql:5.6
    env_file:
      - ./.env
    volumes:
      - dc-snipesql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - "3306"

  

volumes:
  dc-snipesql-vol:




