FROM --platform=linux/amd64 mysql:5.6

ENV MYSQL_ROOT_PASSWORD=snipeit \
    MYSQL_DATABASE=snipeit \
    MYSQL_USER=snipeit \
    MYSQL_PASSWORD=snipeit

COPY mysql-snipeit.sql /mysql-snipeit.sql

CMD mysql -u snipeit -psnipeit snipeit < /mysql-snipeit.sql